# Generated by Django 5.0.4 on 2024-05-02 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_employer_company_info_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Cape Town', 'Capetown'), ('Durban', 'Durban'), ('Johannesburg', 'Johannesburg'), ('Gqeberha', 'Gqeberha')], max_length=50)),
                ('job_type', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Onsite', 'Onsite')], max_length=50)),
                ('experience', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer')),
            ],
        ),
    ]
